version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis_meteo
    ports:
      - "6379:6379"
    networks:
      - monreseau1
    volumes:
      - ./redis_data:/data

  meteoapiapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meteoapi_app
    depends_on:
      - redis
    ports:
      - "8080:8080"
    networks:
      - monreseau1
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # Ajoute ici d'autres variables si nécessaire, ex: DATABASE_URL

networks:
  monreseau1:
    driver: bridge
