services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - monreseau1
    volumes:
      - './redis_data:/data'
  meteoapiapp:
    image: goubexlv/meteoapi
    depends_on:
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - monreseau1
  

networks:
  monreseau1:
